export const ROLE_ANCHOR_CANON = [
  "Guide",
  "Helper",
  "Protector",
  "Caregiver",
  "Companion",
  "Witness",
  "Messenger",
  "Authority",
  "Judge",
  "Gatekeeper",
  "Teacher",
  "Threat",
  "Pursuer",
  "Deceiver",
  "Host",
  "Explorer",
  "Seeker",
  "Initiator",
  "Transformer",
  "Healer",
  "Provider",
  "Leader",
  "Follower",
  "Servant",
  "Mediator",
  "Investigator",
  "Saboteur",
  "Tempter",
  "Creator",
  "Herald",
  "Trickster",
  "Prophet",
  "Rebel",
  "Martyr",
] as const;

export const STRUCTURE_ANCHOR_CANON = [
  "Search",
  "Journey",
  "Exploration",
  "Pursuit",
  "Escape",
  "Return",
  "Arrival",
  "Connection",
  "Threatening",
  "Conflict",
  "Obstruction",
  "Separation",
  "Loss",
  "Containment",
  "Protection",
  "Transition",
  "Transformation",
  "Revelation",
  "Recovery",
  "Investigation",
  "Guidance",
  "Cooperation",
  "Competition",
  "Exchange",
  "Communication",
  "Waiting",
  "Decision",
  "Care",
  "Test",
  "Sabotage",
  "Temptation",
  "Initiation",
  "Repair",
  "Liberation",
  "Ritual",
  "Quest",
  "Judgment",
  "Betrayal",
  "Sacrifice",
  "Resurrection",
  "Destiny",
  "Apocalypse",
] as const;

const ROLE_ANCHOR_CANON_SET = new Set<string>(ROLE_ANCHOR_CANON);
const STRUCTURE_ANCHOR_CANON_SET = new Set<string>(STRUCTURE_ANCHOR_CANON);

export function isCanonicalRoleAnchorIdentityLabel(label: string): boolean {
  return ROLE_ANCHOR_CANON_SET.has(label);
}

export function isCanonicalStructureAnchorIdentityLabel(label: string): boolean {
  return STRUCTURE_ANCHOR_CANON_SET.has(label);
}
